
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework;


namespace cfg
{
public sealed partial class I18nCfg : Framework.BeanBase
{
    public I18nCfg(ByteBuf _buf) 
    {
        Key = _buf.ReadString();
        Value = _buf.ReadString();
    }

    public static I18nCfg DeserializeI18nCfg(ByteBuf _buf)
    {
        return new I18nCfg(_buf);
    }

    public readonly string Key;
    public readonly string Value;
   
    public const int __ID__ = 1821149510;
    public override int GetTypeId() => __ID__;

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "en:" + Value + ","
        + "}";
    }
}
}

