
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework;
using System;
using System.IO;

namespace cfg
{
    public partial class TbI18nCfg : TableBase
    {
        private System.Collections.Generic.Dictionary<string, I18nCfg> _dataMap;
        private System.Collections.Generic.List<I18nCfg> _dataList;
        private Func<string, MemoryStream> _streamLoader;
        private string _fileName;
    
        public override void Initialize(string name, Func<string, MemoryStream> streamLoader)
        {
            _fileName = name;
            _streamLoader = streamLoader;
            _dataMap = new System.Collections.Generic.Dictionary<string, I18nCfg>();
            _dataList = new System.Collections.Generic.List<I18nCfg>();
            LoadAll();
        }

        private void LoadAll()
        {
            var stream = _streamLoader?.Invoke($"{_fileName}.bytes");
            var byteBuf = new ByteBuf(stream.ToArray());
            for (int n = byteBuf.ReadSize(); n > 0; --n)
            {
                I18nCfg v;
                v = global::cfg.I18nCfg.DeserializeI18nCfg(byteBuf);
                _dataList.Add(v);
                _dataMap.Add(v.Key, v);
            }
        }
    
        public System.Collections.Generic.Dictionary<string, I18nCfg> DataMap => _dataMap;
        public System.Collections.Generic.List<I18nCfg> DataList => _dataList;
    
        public I18nCfg Get(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    
    }

}

